### ISSUE TITLE
Null pointer exception when trying to start clerk, running `bb clerk-watch`

### ISSUE THREAD

**Issue by Schaechtle** [InferenceQL/gen.clj#33]
Just pulled the tip of main, I am getting
```
$ bb clerk-watch
Execution error (NullPointerException) at gen.dynamic.choice_map.ChoiceMap/iterator (choice_map.clj:90).
null

Full report at:
/tmp/clojure-12396741036507490247.edn
Error while executing task: clerk-watch
```
Attaching full error report (has to be .txt according to GitHub).
[clojure-12396741036507490247.edn.txt](https://github.com/InferenceQL/gen.clj/files/12448518/clojure-12396741036507490247.edn.txt)

**Comment by sritchie** [comment]
I'll get that patched today, I found that error in my SCI branch. The fix is in the choicemap impl, adding an if-let to the result of .seq.
